name: 💡 Make a suggestion
description: Suggest a change on the current behavior, a completely new feature, or something else.
lables:
  - enhancement
body:
  - type: markdown
    attributes:
      value: |
        Thank you for filling out a feature request for Paper! Please be as detailed as possible so that we may consider and review the request easier.
        We ask that you search all the issues to avoid a duplicate feature request. If one exists, please reply if you have anything to add.
        Before requesting a new feature, please make sure you are using the latest version and that the feature you are requesting is not already in Paper.
  - type: textarea
    attributes:
      label: Why?
      description: Please tell us a little bit about why you want to change or add something. You can also paste images here.
    validations:
      required: true
  - type: textarea
    attributes:
      label: What and How?
      description: How should the plugin behave after the change / what should it do differently than before? If you already have a concrete solution in mind, what does it look like?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Are there alternatives?
      description: Maybe we can't implement your suggestion exactly like that. Can you think of alternative approaches that might work as well, or do you currently use other ways that work quite well for you?
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Checks
      description: "To help us avoid reading the same ideas over and over, please check the following before submitting:"
      options:
        - label: I have used the search at least once to check if my idea has already been suggested and perhaps already implemented.
          required: true
  - type: textarea
    attributes:
      label: Anything else
      description: |
        If want to add anything else that might help us understand your idea, there's plenty of room for it here. 😉
    validations:
      required: false